# Site settings
title: Miguel Gamboa
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
description: "Miguel Gamboa web site"
#baseurl: "/startbootstrap-clean-blog-jekyll"
#url: "http://yourdomain.com"
baseurl: ""
url: "http://fmcarvalho.github.io/"
twitter_username: gamboacarvalho
github_username:  fmcarvalho
facebook_username:  gamboacarvalho
linkedin_username:  gamboacarvalho
instagram_username:  gamboacarvalho
imdb_username:  ls072050509
stackoverflow_username: users/1140754/miguel-gamboa
citations_username: HldfYegAAAAJ

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: "/blog/page:num/"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
